[package]
name = "archimedes_migrations"
version = "0.0.0"
edition = "2021"

[features]
default = ["runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]

[dependencies]
sqlx = "0.6.2"
tracing = "0.1.37"

[dev-dependencies]
tokio = "1.23.0"
