[package]
name = "archimedes_migrations"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Migrations package for archimedes, a high performance Rust/PostgreSQL job queue"
homepage = "docs.rs/archimedes_migrations"
documentation = "docs.rs/archimedes_migrations"
repository = "https://github.com/leo91000/archimedes/crates/migrations"
keywords = ["worker", "scheduler", "job scheduler", "async", "multithread"]
categories = ["job-scheduler", "worker", "multithread", "async", "tokio"]
readme = "README.md"

[features]
default = ["runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]

[dependencies]
sqlx = "0.6.2"
tracing = "0.1.37"

[dev-dependencies]
tokio = "1.23.0"
