[package]
name = "archimedes"
version = "0.1.0"
edition = "2021"

[features]
default = ["runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std-rustls"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std-native-tls"]

[dependencies]
async-trait = "0.1.58"
getset = "0.1.2"
include_dir = { version = "0.7.3", features = ["glob"] }
sqlx = { version = "0.6.2", features = ["postgres", "json"] }
thiserror = "1.0.37"
typed-builder = "0.11.0"
