[package]
name = "archimedes_crontab_parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Crontab parsing package for archimedes, a high performance Rust/PostgreSQL job queue"
homepage = "docs.rs/archimedes_crontab_parser"
documentation = "docs.rs/archimedes_crontab_parser"
repository = "https://github.com/leo91000/archimedes/crates/crontab_parser"
keywords = ["worker", "scheduler", "job-scheduler", "async", "multithread"]
categories = ["job-scheduler", "worker", "multithread", "async", "tokio"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
archimedes_crontab_types = { path = "../crontab_types" }
json5 = "0.4.1"
nom = "7.1.1"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
serde_qs = "0.10.1"
thiserror = "1.0.38"
