[package]
name = "crontab_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json5 = "0.4.1"
nom = "7.1.1"
once_cell = "1.16.0"
regex = "1.7.0"
serde = "1.0.148"
serde_json = "1.0.89"
serde_qs = "0.10.1"
thiserror = "1.0.37"
